name: Nightly Screenshots from Jersey Met Office

# on:
#   schedule:
#     - cron: '0 0 * * *'

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set directory with date
        id: destdir
        run: echo "destdir=$(date +'%Y/%m/met-office/%d')" >> $GITHUB_ENV

      - name: Verify directory exists
        run: mkdir -p skies/${{ env.destdir }}
          
      - name: screenshots-desktop-shipping-forecast
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://www.gov.je/weather/shipping/
          destination: ${{ env.current_date }}-shipping-forecast.png
          full-page: true
          delay: 1

      - name: screenshots-desktop-weather-forecast
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://www.gov.je/weather/
          destination: ${{ env.current_date }}-weather-forecast.png
          full-page: true
          delay: 3

      - name: Copy shipping forecast screenshot into repo
        id: cp-shipping-forecast-screenshots
        run: cp /home/runner/work/_temp/${{ env.current_date }}-shipping-forecast.png /home/runner/work/sky-data/sky-data/skies/${{ env.destdir }}/${{ env.current_date }}-shipping-forecast.png
        
      - name: Copy weather forecast screenshot into repo
        id: cp-weather-forecast-screenshots
        run: cp /home/runner/work/_temp/${{ env.current_date }}-weather-forecast.png /home/runner/work/sky-data/sky-data/skies/${{ env.destdir }}/${{ env.current_date }}-weather-forecast.png          

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '${{ env.current_date }} - Nightly weather and shipping forecasts from jerseymet'
