name: Hourly Data Collection from Jersey Met Office

on:
  schedule:
    - cron: '0 * * * *'

# on:
#   push:
#     branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Download latest satellite image from jersey met service
        run: |
          mkdir -p skies/$(date +'%Y/%m-%B/met-office/%d')
          wget -O skies/$(date +'%Y/%m-%B/met-office/%d')/$(date +'%Y-%m-%d-%H%M-jerseymet-satellite.jpg') https://sojpublicdata.blob.core.windows.net/jerseymet/Satellite10.JPG

      - name: Download latest runway camera image from jersey airport
        run: |
          mkdir -p skies/$(date +'%Y/%m-%B/jersey-airport/%d')
          wget -O skies/$(date +'%Y/%m-%B/jersey-airport/%d')/$(date +'%Y-%m-%d-%H%M-jerseyairport-runwaycam.jpg') https://sojpublicdata.blob.core.windows.net/jerseymet/Webcam/Airport_00001.jpg

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Latest hourly images from jerseymet and jerseyairport
