name: Nightly Screenshots from Jersey Met Office

# on:
#   schedule:
#     - cron: '0 0 * * *'

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Verify directory exists
        run: mkdir -p skies/$(date +'%Y/%m/met-office/%d')

      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set directory with date
        id: destdir
        run: echo "destdir=$(date +'%Y/%m/met-office/%d')" >> $GITHUB_ENV
          
      - name: screenshots-desktop-shipping-forecast
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://www.gov.je/weather/shipping/
          destination: 'skies/${{ env.destdir }}/${{ env.current_date }}-shipping-forecast.png'
          full-page: true
          delay: 2
          # remove-elements: cookiebanner

      - name: screenshots-desktop-weather-forecast
        uses: flameddd/screenshots-ci-action@master
        with:
          source: https://www.gov.je/weather/
          destination: 'skies/${{ env.destdir }}/${{ env.current_date }}-weather-forecast.png'
          full-page: true
          delay: 5
          # remove-elements: cookiebanner

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '${{ env.current_date }} - Nightly weather and shipping forecasts from jerseymet'
