name: Hourly Met Office Data Collection

on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download latest satellite image from jersey met service
        run: |
          mkdir -p skies/$(date +'%Y/%m/met-office/%d')
          wget -O skies/$(date +'%Y/%m/met-office/%d')/$(date +'%Y-%m-%d-%H%M-jerseymet-satellite.jpg') https://sojpublicdata.blob.core.windows.net/jerseymet/Satellite10.JPG
